version: '3'
services:
    backend:
        build:
            context: backend
            dockerfile: Dockerfile.backend
        environment:
            - APP_ENV=dev
            - PYTHONUNBUFFERED=1
        ports:
            - "40001:40001"
        volumes:
            - ./backend:/code
    worker:
        build:
            context: backend
            dockerfile: Dockerfile.worker
        environment:
            - APP_ENV=dev
        volumes:
            - ./backend:/code
